### PR TITLE
Tests FTW!

### PR DESCRIPTION
**Pull request by AntoineDao**
Was about time this was setup on the speckle server repo let's be honest. Some features are really hard to monitor and it's difficult for newbs to confidently propose code changes without tests to make sure stuff still works.

This WIP but I'm hoping that creating the PR wakes up Appveyor to see if it works with the new config. Maybe it won't wake up in which case you'll have to take my word for it that it works :smile:

### CODE REVIEW

**Comment by AntoineDao** [comment]
GREAT SUCCESS! The tests are running. And fail because I noticed what I think is a bug in the account search function 😉

**Comment by didimitrie** [comment]
I can't wait to pull this and give it a spin, to be honest...

**Comment by AntoineDao** [comment]
I mean... I'm finishing up projects just now. If you wanna merge it in afterwards to start working on the other tests that are missing feel free to. What do you think?

Or you could pull from my fork/branch and PR into that?

**Comment by AntoineDao** [comment]
Right @didimitrie I think this is as much as I can stomach for now. Writing tests for the Projects API is gnarly as #£$%^& and partially unsuccessful as you'll see when scanning over test results. 

As of now I reckon it's worth merging this in some way shape or form either in it's own feature branch that others can commit to or in master (however than means any deployment is pretty much blocked until all tests pass.

Let us know what you think the best way forward is. I'm happy to help write some more tests but honestly it's not something I'll be able to do on my own :/

**Comment by AntoineDao** [comment]
No rush mate, this PR can stay hanging. Just notifying you i'm done with it for now😛

**Comment by AntoineDao** [comment]
Oh SNAP! That's a :heavy_check_mark: !!

**Comment by AntoineDao** [comment]
Oh SNAP! That's a :heavy_check_mark: !!

**Comment by AntoineDao** [comment]
Oh SNAP! That's a :heavy_check_mark: !!

(PS: cheeky last minute test after merging from master... fun)

**Pull request merged**
