### PR TITLE
feat(continuous deployment): implement semantic-release

### PR DESCRIPTION
**Pull request by AntoineDao**
Semantic-release now creates github releases and deploys new versioned docker containers.

This PR proposed we start using semantic release as discussed in #131 in order to automatically deploy versioned containers (it will also create github releases automatically based on commit messages).

If this is something we are happy to merge then the following must be done:
1. Add secure env vars for `GH_TOKEN` and `DOCKER_PASSWORD` (for @botsalot ) [here](https://ci.appveyor.com/project/SpeckleWorks/speckleserver/settings/environment). I don't have access to the appveyor settings so cannot do it unfortunately
2. The hardest part => Convince all the people contributing to SpeckleServer to start using Angular commit style so versions get bumped automatically and release notes get generated by `semantic-release`. Following this commit style is really easy if using [`comittizen`](https://github.com/commitizen/cz-cli), which can be installed running the following command:
```console
npm install -g commitizen cz-conventional-changelog && echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
```

Commits can then be made by typing the following command on your command line:
```console
git add .
git cz
# Follow comittizen prompts
```

solves #131

### CODE REVIEW

**Comment by AntoineDao** [comment]
Please feel free to pull in anyone who is relevant to this conversation 😄

**Comment by didimitrie** [comment]
I haven't forgotten about this, it's just a pain recently to make time for this. We need to ping @mswaidan for sure, and any other server maintainers out there. will do on slack...

**Comment by AntoineDao** [comment]
No rush and no worries. I'd talked about it in that issue and only just got around to pinging a proposed fix for it. If anyone's interested in getting a feel for what semantic release looks like in practice check out some of the ladybug tools repos (Honeybee, Ladybug, Dragonfly for example all use it)

**Comment by mswaidan** [comment]
I'm on board

**Comment by didimitrie** [comment]
Cool, then i think we can go ahead. @AntoineDao, i've invited you to the the org team on appveyor. i've installed commitizen, and it seems fine. A question: would this be worth it?
- add `commitizen` as a dev dependency (npm i --save-dev commitizen)
- add a npm script for comitting, that makes sure it calls `git cz`. 

Or something on the lines of :)

**Comment by AntoineDao** [comment]
I haven't set it up as a Dev dependency before but it seems worth it judging by this [article](https://link.medium.com/ppMQzV70EY)

**Comment by AntoineDao** [comment]
I'll do it just now after setting up appveyor.

**Comment by AntoineDao** [comment]
Right, that's the `appveyor.yml` file fixed. Please someone double check I didn't break anything in the process :see_no_evil: I have also added the required env vars to the appveyor config so if we merge this into master we should be good to go! (famous last words...)

**Comment by didimitrie** [comment]
let's find out what breaks :)

**Comment by AntoineDao** [comment]
Somehow env vars aren't happening... BOOO! I'll set them up outside of the appveyor file and see what gives.

**Comment by didimitrie** [comment]
yeah, was just fiddling with that now, but need to run to work. Somehow it fails at the npm publish moment, which is actually not really needed (i was trying to see how we can skip that step)

**Pull request merged**
